#!/usr/bin/env bash
# initialize.sh - create local devcontainer files and prepare worktrees
#
# Why this exists:
# - `devcontainer.json` includes `../compose.local.yml`, so a fresh consuming
#   checkout needs that root-level local file before the Compose project can be
#   resolved.
# - `../.local.env` carries machine-local runtime values and should be created
#   from the template only once.
# - Git worktrees are selected through BRANCH while the Dev Containers CLI or VS
#   Code still starts from the repository root.
# - BRANCH lets `initializeCommand` create or reuse a managed worktree before
#   the container starts while VS Code is still opened at the repository root.
# - `.gen.env` and `compose.local.gen.yml` are generated kit-owned files under
#   `.devcontainer/`; users should edit root `.local.env` and `compose.local.yml`
#   instead.
# - The script runs as a Dev Containers `initializeCommand` on the host and must
#   stay idempotent, non-interactive, and safe for repeated starts.
#
# Related files:
# - devcontainer.json
# - docker-compose.yml
# - compose.local.gen.yml
# - compose.local.yml.example
# - .gen.env
# - .local.env.example

set -euo pipefail

script_dir="$(dirname "$(readlink -f "$0")")"
checkout_dir="$(dirname "$script_dir")"

copy_if_missing() {
  local source_file="$1"
  local target_file="$2"

  if [ -e "$target_file" ] || [ -L "$target_file" ]; then
    return 0
  fi

  cp "$source_file" "$target_file"
}

repo_root() {
  git -C "$checkout_dir" rev-parse --show-toplevel
}

slugify_hostname_part() {
  local value="${1:-detached}"

  value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')"
  value="${value#-}"
  value="${value%-}"

  if [ -z "$value" ]; then
    value="detached"
  fi

  printf '%s\n' "$value"
}

current_branch_name() {
  local root_dir="$1"
  local branch_name=""

  branch_name="$(git -C "$root_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"

  if [ -z "$branch_name" ] || [ "$branch_name" = "HEAD" ]; then
    branch_name="detached"
  fi

  printf '%s\n' "$branch_name"
}

generated_hostname() {
  local root_dir="$1"
  local branch_name="$2"
  local host_part=""
  local repo_part=""
  local branch_part=""

  host_part="$(slugify_hostname_part "$(hostname -s 2>/dev/null || hostname)")"
  repo_part="$(slugify_hostname_part "$(basename "$root_dir")")"
  branch_part="$(slugify_hostname_part "${branch_name:-$(current_branch_name "$root_dir")}")"

  printf '%s-%s-%s\n' "$host_part" "$repo_part" "$branch_part"
}

write_generated_env() {
  local target_file="$1"
  local root_dir="$2"
  local branch_name="$3"
  local host_name=""
  local repo_name=""
  local selected_branch=""
  local container_hostname=""
  local user_name=""
  local group_name=""
  local uid=""

  host_name="$(slugify_hostname_part "$(hostname -s 2>/dev/null || hostname)")"
  repo_name="$(slugify_hostname_part "$(basename "$root_dir")")"
  selected_branch="${branch_name:-$(current_branch_name "$root_dir")}"
  container_hostname="$(generated_hostname "$root_dir" "$selected_branch")"
  user_name="${USER:-$(id -un)}"
  group_name="$(id -gn)"
  uid="$(id -u)"

  cat >"$target_file" <<EOF
# .gen.env - generated by .devcontainer/initialize.sh
#
# Do not edit manually. Local environment overrides belong in ../.local.env.
DEVCONTAINER_HOST_NAME=$host_name
DEVCONTAINER_REPO_NAME=$repo_name
DEVCONTAINER_BRANCH_NAME=$(slugify_hostname_part "$selected_branch")
DEVCONTAINER_HOSTNAME=$container_hostname
DEVCONTAINER_USER=$user_name
DEVCONTAINER_GROUP=$group_name
DEVCONTAINER_UID=$uid
DEVCONTAINER_GID=$uid
EOF
}

write_generated_compose() {
  local target_file="$1"
  local container_hostname="$2"
  local user_name=""
  local group_name=""
  local uid=""

  user_name="${USER:-$(id -un)}"
  group_name="$(id -gn)"
  uid="$(id -u)"

  cat >"$target_file" <<EOF
# compose.local.gen.yml - generated by .devcontainer/initialize.sh
#
# Do not edit manually. Local Compose overrides belong in ../compose.local.yml.
services:
  workspace:
    build:
      args:
        CONTAINER_USER: $user_name
        CONTAINER_GROUP: $group_name
        CONTAINER_UID: "$uid"
        CONTAINER_GID: "$uid"
    hostname: $container_hostname
    user: "$uid:$uid"
EOF
}

ensure_root_compose_local() {
  local root_dir="$1"

  copy_if_missing "$root_dir/.devcontainer/compose.local.yml.example" "$root_dir/compose.local.yml"
}

ensure_root_local_env() {
  local root_dir="$1"

  copy_if_missing "$root_dir/.devcontainer/.local.env.example" "$root_dir/.local.env"
}

ensure_worktree() {
  local root_dir="$1"
  local branch="$2"
  local slug="$3"
  local worktree_path="$root_dir/.worktrees/$slug"

  git check-ref-format --branch "$branch" >/dev/null
  mkdir -p "$(dirname "$worktree_path")"

  if [ -e "$worktree_path" ]; then
    [ "$(git -C "$worktree_path" rev-parse --show-toplevel)" = "$worktree_path" ]
  elif git -C "$root_dir" show-ref --verify --quiet "refs/heads/$branch"; then
    git -C "$root_dir" worktree add "$worktree_path" "$branch" >&2
  else
    git -C "$root_dir" worktree add -b "$branch" "$worktree_path" >&2
  fi

  if [ -f "$worktree_path/.gitmodules" ]; then
    git -C "$worktree_path" -c protocol.file.allow=always submodule update --init --recursive >&2
  fi

  printf '%s\n' "$worktree_path"
}

ensure_worktree_local_env_link() {
  local root_dir="$1"
  local worktree_path="$2"
  local link_path="$worktree_path/.local.env"
  local link_target=""

  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    return 0
  fi

  link_target="$(realpath --relative-to="$(dirname "$link_path")" "$root_dir/.local.env")"
  ln -s "$link_target" "$link_path"
}

prepare_selected_worktree() {
  local root_dir="$1"
  local branch_name="$2"
  local worktree_path=""

  worktree_path="$(ensure_worktree "$root_dir" "$branch_name" "$branch_name")"

  ensure_worktree_local_env_link "$root_dir" "$worktree_path"
}

main() {
  local root_dir=""
  local branch_name=""

  case "${1:-}" in
    "")
      root_dir="$(repo_root)"
      branch_name="${BRANCH:-}"

      ensure_root_compose_local "$root_dir"
      ensure_root_local_env "$root_dir"
      write_generated_env "$script_dir/.gen.env" "$root_dir" "$branch_name"
      write_generated_compose "$script_dir/compose.local.gen.yml" "$(generated_hostname "$root_dir" "$branch_name")"

      if [ -n "$branch_name" ]; then
        prepare_selected_worktree "$root_dir" "$branch_name"
      fi
      ;;
    *)
      printf 'Usage: %s\n' "$0" >&2
      exit 1
      ;;
  esac
}

main "$@"
