#!/usr/bin/env bash
# chrome-launcher.sh - verify visible Chrome launcher environment handling
#
# Why this exists:
# - protects the VS Code reopen path where initializeCommand refreshes the
#   mounted `.devcontainer/.env` but an existing container keeps old environment
#   variables.
# - avoids needing a real X server by replacing `google-chrome` with a tiny fake
#   command that records the DISPLAY value and Chrome args it received.
#
# Related files:
# - ../scripts/chrome.sh
# - ../initialize.sh

set -euo pipefail

script_dir="$(dirname "$(readlink -f "$0")")"

# shellcheck source=./helpers.sh
source "$script_dir/helpers.sh"

local_suite=0
if [ -z "${suite_tmp_dir:-}" ]; then
  setup_suite
  local_suite=1
fi

if [ "$local_suite" -eq 1 ]; then
  trap cleanup_suite EXIT
fi

fixture_dir="$suite_tmp_dir/chrome-launcher-fixture"
fake_bin="$suite_tmp_dir/chrome-launcher-bin"
capture_file="$suite_tmp_dir/chrome-launcher-display.txt"
args_capture_file="$suite_tmp_dir/chrome-launcher-args.txt"
profile_dir="$suite_tmp_dir/chrome-cdp-profile"

mkdir -p "$fixture_dir/.devcontainer" "$fake_bin"

cat >"$fixture_dir/.devcontainer/.env" <<'EOF'
# .env - generated by .devcontainer/initialize.sh
DEVCONTAINER_DISPLAY=localhost:77.0
EOF

cat >"$fake_bin/google-chrome" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "${DISPLAY:-}" >"$CHROME_LAUNCHER_CAPTURE"
printf '%s\n' "$@" >"$CHROME_LAUNCHER_ARGS_CAPTURE"
EOF
chmod +x "$fake_bin/google-chrome"

PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_CDP_PROFILE_DIR="$profile_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" about:blank

[[ "$(<"$capture_file")" = "localhost:77.0" ]] \
  || fail "chrome launcher did not refresh DISPLAY from generated workspace env"
grep -Fx -- "--user-data-dir=$profile_dir" "$args_capture_file" >/dev/null \
  || fail "chrome launcher did not use CHROME_CDP_PROFILE_DIR as visible profile"

PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_CDP_PROFILE_DIR="$profile_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  DISPLAY=localhost:1.0 \
  "$project_root/scripts/chrome.sh" about:blank

[[ "$(<"$capture_file")" = "localhost:77.0" ]] \
  || fail "chrome launcher did not replace stale DISPLAY from generated workspace env"

pass "chrome launcher refreshes visible DISPLAY from generated workspace env"
