#!/usr/bin/env bash
# chrome-launcher.sh - verify reconnect-safe Chrome display selection
#
# Why this exists:
# - proves an existing container replaces stale Compose environment from its
#   workspace-local `.devcontainer/.env` after a VS Code SSH reconnect
# - verifies SSH-loopback displays are probed and recover through current
#   Xauthority cookies before Google Chrome starts
# - runs two launcher instances in parallel to protect per-workspace display,
#   Xauthority, profile, and capture isolation on a shared host
# - keeps deterministic fake-browser checks separate from the real Chrome plus
#   Wayland compositor regression in `browser-smoke.sh`
#
# Related files:
# - ../scripts/chrome.sh
# - ../initialize.sh
# - ./browser-smoke.sh

set -euo pipefail

script_dir="$(dirname "$(readlink -f "$0")")"

# shellcheck source=./helpers.sh
source "$script_dir/helpers.sh"

local_suite=0
if [ -z "${suite_tmp_dir:-}" ]; then
  setup_suite
  local_suite=1
fi

fixture_a="$suite_tmp_dir/chrome-launcher-workspace-a"
fixture_b="$suite_tmp_dir/chrome-launcher-workspace-b"
fake_bin="$suite_tmp_dir/chrome-launcher-bin"
reachable_displays="$suite_tmp_dir/reachable-displays.txt"
wayland_runtime_dir="/tmp/chrome-launcher-wayland.$$"
wayland_socket_name="vscode-wayland-test.sock"
wayland_socket_path="$wayland_runtime_dir/$wayland_socket_name"
local_display_number="$((20000 + $$ % 10000))"
local_x11_socket="/tmp/.X11-unix/X$local_display_number"
invalid_display_number="$((30000 + $$ % 10000))"
socket_pids=()
created_x11_dir=0

cleanup_chrome_launcher() {
  local socket_pid=""

  for socket_pid in "${socket_pids[@]}"; do
    kill "$socket_pid" >/dev/null 2>&1 || true
    wait "$socket_pid" >/dev/null 2>&1 || true
  done

  rm -f "$local_x11_socket"
  rm -rf "$wayland_runtime_dir"
  if [ "$created_x11_dir" -eq 1 ]; then
    rmdir /tmp/.X11-unix >/dev/null 2>&1 || true
  fi

  if [ "$local_suite" -eq 1 ]; then
    cleanup_suite
  fi
}
trap cleanup_chrome_launcher EXIT

start_unix_socket() {
  local socket_path="$1"
  local socket_pid=""

  mkdir -p "$(dirname "$socket_path")"
  rm -f "$socket_path"
  socat "UNIX-LISTEN:$socket_path,fork" EXEC:/bin/true >/dev/null 2>&1 &
  socket_pid="$!"
  socket_pids+=("$socket_pid")

  for _ in $(seq 1 50); do
    [ ! -S "$socket_path" ] || return 0
    sleep 0.1
  done

  fail "Unix socket was not created: $socket_path"
}

write_generated_display() {
  local fixture_dir="$1"
  local display_value="$2"
  local xauthority_file="${3:-}"
  local wayland_display_value="${4:-}"
  local wayland_runtime_value="${5:-}"

  mkdir -p "$fixture_dir/.devcontainer"
  cat >"$fixture_dir/.devcontainer/.env" <<EOF
# .env - generated by .devcontainer/initialize.sh
DEVCONTAINER_DISPLAY=$display_value
DEVCONTAINER_XAUTHORITY=$xauthority_file
DEVCONTAINER_WAYLAND_DISPLAY=$wayland_display_value
DEVCONTAINER_WAYLAND_RUNTIME_DIR=$wayland_runtime_value
EOF
}

write_xauthority() {
  local target_file="$1"
  shift
  local display_number=""
  local cookie_index=1

  rm -f "$target_file"
  touch "$target_file"
  for display_number in "$@"; do
    xauth -f "$target_file" add \
      "fixture/unix:$display_number" \
      MIT-MAGIC-COOKIE-1 \
      "$(printf '%032x' "$cookie_index")" >/dev/null 2>&1
    cookie_index="$((cookie_index + 1))"
  done
  chmod 600 "$target_file"
}

run_launcher() {
  local fixture_dir="$1"
  local capture_file="$2"
  local args_capture_file="$3"
  shift 3

  PATH="$fake_bin:$PATH" \
    DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
    CHROME_LAUNCHER_CAPTURE="$capture_file" \
    CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
    FAKE_XDPYINFO_REACHABLE_FILE="$reachable_displays" \
    FAKE_XDPYINFO_REQUIRE_NORMALIZED_DISPLAY="${FAKE_XDPYINFO_REQUIRE_NORMALIZED_DISPLAY:-}" \
    FAKE_XDPYINFO_SOURCE_AUTHORITY="${FAKE_XDPYINFO_SOURCE_AUTHORITY:-}" \
    "$project_root/scripts/chrome.sh" "$@"
}

assert_no_wayland_ozone_arg() {
  local args_capture_file="$1"

  if grep -Fx -- "--ozone-platform=wayland" "$args_capture_file" >/dev/null; then
    fail "chrome launcher selected Wayland unexpectedly"
  fi
}

mkdir -p "$fixture_a/.devcontainer" "$fixture_b/.devcontainer" "$fake_bin" "$wayland_runtime_dir"
chmod 700 "$wayland_runtime_dir"
: >"$reachable_displays"
unset DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR XAUTHORITY

cat >"$fake_bin/xdpyinfo" <<'EOF'
#!/usr/bin/env bash
if [ -n "${FAKE_XDPYINFO_REQUIRE_NORMALIZED_DISPLAY:-}" ] \
  && [ "${DISPLAY:-}" = "$FAKE_XDPYINFO_REQUIRE_NORMALIZED_DISPLAY" ] \
  && [ "${XAUTHORITY:-}" = "${FAKE_XDPYINFO_SOURCE_AUTHORITY:-}" ]; then
  exit 1
fi
grep -Fx -- "${DISPLAY:-}" "$FAKE_XDPYINFO_REACHABLE_FILE" >/dev/null
EOF
chmod +x "$fake_bin/xdpyinfo"

cat >"$fake_bin/google-chrome" <<'EOF'
#!/usr/bin/env bash
{
  printf 'DISPLAY=%s\n' "${DISPLAY:-}"
  printf 'WAYLAND_DISPLAY=%s\n' "${WAYLAND_DISPLAY:-}"
  printf 'XDG_RUNTIME_DIR=%s\n' "${XDG_RUNTIME_DIR:-}"
  printf 'XAUTHORITY=%s\n' "${XAUTHORITY:-}"
} >"$CHROME_LAUNCHER_CAPTURE"
printf '%s\n' "$@" >"$CHROME_LAUNCHER_ARGS_CAPTURE"
EOF
chmod +x "$fake_bin/google-chrome"

log "checking reconnect refresh and parallel workspace isolation"
authority_a="$fixture_a/.devcontainer/.Xauthority.gen"
authority_b="$fixture_b/.devcontainer/.Xauthority.gen"
capture_a="$suite_tmp_dir/chrome-launcher-a-environment.txt"
capture_b="$suite_tmp_dir/chrome-launcher-b-environment.txt"
args_a="$suite_tmp_dir/chrome-launcher-a-args.txt"
args_b="$suite_tmp_dir/chrome-launcher-b-args.txt"
write_xauthority "$authority_a" 82
write_xauthority "$authority_b" 83
write_generated_display "$fixture_a" "localhost:82.0" "$authority_a"
write_generated_display "$fixture_b" "localhost:83.0" "$authority_b"
printf '%s\n' "localhost:82.0" "localhost:83.0" >"$reachable_displays"

DISPLAY=localhost:10.0 \
  run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank &
launcher_a_pid="$!"
DISPLAY=localhost:11.0 \
  run_launcher "$fixture_b" "$capture_b" "$args_b" about:blank &
launcher_b_pid="$!"
wait "$launcher_a_pid"
wait "$launcher_b_pid"

grep -Fx "DISPLAY=localhost:82.0" "$capture_a" >/dev/null \
  || fail "workspace A did not replace stale container DISPLAY after reconnect"
grep -Fx "DISPLAY=localhost:83.0" "$capture_b" >/dev/null \
  || fail "workspace B did not keep its independent DISPLAY"
grep -Fx "XAUTHORITY=$authority_a" "$capture_a" >/dev/null \
  || fail "workspace A did not use its generated Xauthority"
grep -Fx "XAUTHORITY=$authority_b" "$capture_b" >/dev/null \
  || fail "workspace B did not use its generated Xauthority"
grep -Fx -- "--user-data-dir=$fixture_a/.chrome" "$args_a" >/dev/null \
  || fail "workspace A did not use its own Chrome profile"
grep -Fx -- "--user-data-dir=$fixture_b/.chrome" "$args_b" >/dev/null \
  || fail "workspace B did not use its own Chrome profile"
for expected_arg in \
  --disable-background-networking \
  --disable-breakpad \
  --disable-component-update \
  --disable-default-apps \
  --disable-extensions \
  --disable-gpu \
  --disable-notifications \
  --disable-search-engine-choice-screen \
  --disable-sync \
  --disable-translate \
  --metrics-recording-only \
  --mute-audio \
  --password-store=basic; do
  grep -Fx -- "$expected_arg" "$args_a" >/dev/null \
    || fail "chrome launcher did not pass visible performance flag: $expected_arg"
done

explicit_profile_dir="$suite_tmp_dir/explicit-chrome-profile"
run_launcher "$fixture_b" "$capture_b" "$args_b" \
  --user-data-dir="$explicit_profile_dir" about:blank
grep -Fx -- "--user-data-dir=$explicit_profile_dir" "$args_b" >/dev/null \
  || fail "chrome launcher did not forward explicit caller profile"
if grep -Fx -- "--user-data-dir=$fixture_b/.chrome" "$args_b" >/dev/null; then
  fail "chrome launcher added workspace profile despite explicit caller profile"
fi
[[ "$(grep -c '^--user-data-dir' "$args_b")" = "1" ]] \
  || fail "chrome launcher passed more than one user data directory"

log "checking SSH X11 recovery from current Xauthority cookies"
recovery_capture="$suite_tmp_dir/chrome-launcher-recovery-environment.txt"
recovery_args="$suite_tmp_dir/chrome-launcher-recovery-args.txt"
write_xauthority "$authority_a" 70 72
write_generated_display "$fixture_a" "localhost:72.0" "$authority_a"
printf '%s\n' "localhost:72.0" >"$reachable_displays"
FAKE_XDPYINFO_REQUIRE_NORMALIZED_DISPLAY=localhost:72.0 \
  FAKE_XDPYINFO_SOURCE_AUTHORITY="$authority_a" \
  DISPLAY=localhost:9.0 \
  run_launcher "$fixture_a" "$recovery_capture" "$recovery_args" about:blank

grep -Fx "DISPLAY=localhost:72.0" "$recovery_capture" >/dev/null \
  || fail "chrome launcher did not recover the reachable SSH X11 candidate"
recovered_authority="$(extract_key_value "$(<"$recovery_capture")" XAUTHORITY)"
[ "$recovered_authority" != "$authority_a" ] \
  || fail "SSH recovery reused the shared source Xauthority instead of a temporary file"
case "$recovered_authority" in
  /tmp/chrome-xauthority.*|"$wayland_runtime_dir"/chrome-xauthority.*) ;;
  *) fail "SSH recovery used an unexpected Xauthority path: $recovered_authority" ;;
esac
rm -f "$recovered_authority"

log "checking Wayland preference over invalid X11"
start_unix_socket "$wayland_socket_path"
write_generated_display \
  "$fixture_a" \
  ":$invalid_display_number" \
  "$authority_a" \
  "$wayland_socket_name" \
  "$wayland_runtime_dir"
WAYLAND_DISPLAY="$wayland_socket_name" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  DISPLAY=localhost:1.0 \
  run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank

grep -Fx "DISPLAY=" "$capture_a" >/dev/null \
  || fail "chrome launcher did not remove invalid X11 when selecting Wayland"
grep -Fx "WAYLAND_DISPLAY=$wayland_socket_name" "$capture_a" >/dev/null \
  || fail "chrome launcher did not preserve WAYLAND_DISPLAY"
grep -Fx -- "--ozone-platform=wayland" "$args_a" >/dev/null \
  || fail "chrome launcher did not force the Wayland Ozone backend"

log "checking local and caller-managed remote X11 behavior"
if [ ! -d /tmp/.X11-unix ]; then
  mkdir -m 1777 /tmp/.X11-unix
  created_x11_dir=1
fi
start_unix_socket "$local_x11_socket"
write_generated_display "$fixture_a" ":$local_display_number.0" "$authority_a"
run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank
grep -Fx "DISPLAY=:$local_display_number.0" "$capture_a" >/dev/null \
  || fail "chrome launcher did not preserve local X11 with a real socket"
assert_no_wayland_ozone_arg "$args_a"

write_generated_display "$fixture_a" "host.docker.internal:4.0" "$authority_a"
run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank
grep -Fx "DISPLAY=host.docker.internal:4.0" "$capture_a" >/dev/null \
  || fail "chrome launcher did not preserve caller-managed remote X11"

log "checking unusable local X11 and Wayland diagnostics"
missing_backend_error="$suite_tmp_dir/chrome-launcher-missing-backend-error.txt"
write_generated_display \
  "$fixture_a" \
  ":$invalid_display_number" \
  "$authority_a" \
  "missing-wayland.sock" \
  "$wayland_runtime_dir"
rm -f "$capture_a" "$args_a" "$missing_backend_error"
set +e
WAYLAND_DISPLAY="missing-wayland.sock" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank 2>"$missing_backend_error"
missing_backend_status="$?"
set -e
[[ "$missing_backend_status" -ne 0 ]] || fail "chrome launcher accepted missing local display sockets"
[ ! -e "$capture_a" ] || fail "chrome launcher started Google Chrome with missing local display sockets"
grep -F "Detected DISPLAY=:$invalid_display_number, but /tmp/.X11-unix/X$invalid_display_number is not available inside the container." "$missing_backend_error" >/dev/null \
  || fail "chrome launcher did not explain the missing local X11 socket"
grep -F "Detected WAYLAND_DISPLAY=missing-wayland.sock, but no socket is available at $wayland_runtime_dir/missing-wayland.sock." "$missing_backend_error" >/dev/null \
  || fail "chrome launcher did not explain the missing Wayland socket"

log "checking stale SSH X11 rejection before Google Chrome starts"
error_capture="$suite_tmp_dir/chrome-launcher-error.txt"
write_xauthority "$authority_a" 90 91
write_generated_display "$fixture_a" "localhost:90.0" "$authority_a"
: >"$reachable_displays"
rm -f "$capture_a" "$args_a" "$error_capture"
set +e
WAYLAND_DISPLAY="$wayland_socket_name" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  DISPLAY=localhost:10.0 \
  run_launcher "$fixture_a" "$capture_a" "$args_a" about:blank 2>"$error_capture"
launcher_status="$?"
set -e

[[ "$launcher_status" -ne 0 ]] || fail "chrome launcher accepted stale SSH X11"
[ ! -e "$capture_a" ] || fail "chrome launcher started Google Chrome with stale SSH X11"
grep -F "Detected stale SSH DISPLAY=localhost:90.0; its Xauthority cookie did not pass xdpyinfo." "$error_capture" >/dev/null \
  || fail "chrome launcher did not explain stale SSH X11"
grep -F "SSH X11 candidates tested: localhost:90.0 localhost:90.0" "$error_capture" >/dev/null \
  || fail "chrome launcher did not report tested SSH X11 candidates"

log "checking headless mode remains display-independent"
DISPLAY="localhost:$invalid_display_number.0" \
  WAYLAND_DISPLAY="missing-wayland.sock" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  run_launcher "$fixture_a" "$capture_a" "$args_a" --headless --version
grep -Fx -- "--headless=new" "$args_a" >/dev/null \
  || fail "chrome launcher changed the headless Chrome path"

pass "chrome launcher heals reconnect display state and isolates parallel workspaces"
