#!/usr/bin/env bash
# chrome-launcher.sh - verify Chrome display backend selection and launch defaults
#
# Why this exists:
# - protects the VS Code reopen path where initializeCommand refreshes the
#   mounted `.devcontainer/.env` but an existing container keeps old environment
#   variables.
# - covers backend selection deterministically with real Unix sockets while a
#   fake `google-chrome` records the environment and arguments it received.
# - keeps fast launcher diagnostics separate from the real Chrome plus Wayland
#   compositor regression in `browser-smoke.sh`.
#
# Related files:
# - ../scripts/chrome.sh
# - ../initialize.sh
# - ./browser-smoke.sh

set -euo pipefail

script_dir="$(dirname "$(readlink -f "$0")")"

# shellcheck source=./helpers.sh
source "$script_dir/helpers.sh"

local_suite=0
if [ -z "${suite_tmp_dir:-}" ]; then
  setup_suite
  local_suite=1
fi

fixture_dir="$suite_tmp_dir/chrome-launcher-fixture"
fake_bin="$suite_tmp_dir/chrome-launcher-bin"
capture_file="$suite_tmp_dir/chrome-launcher-environment.txt"
args_capture_file="$suite_tmp_dir/chrome-launcher-args.txt"
error_capture_file="$suite_tmp_dir/chrome-launcher-error.txt"
workspace_profile_dir="$fixture_dir/.chrome"
explicit_profile_dir="$suite_tmp_dir/playwright-mcp-profile"
wayland_runtime_dir="/tmp/chrome-launcher-wayland.$$"
wayland_socket_name="vscode-wayland-test.sock"
wayland_socket_path="$wayland_runtime_dir/$wayland_socket_name"
local_display_number="$((20000 + $$ % 10000))"
local_x11_socket="/tmp/.X11-unix/X$local_display_number"
invalid_display_number="$((30000 + $$ % 10000))"
socket_pids=()
created_x11_dir=0

cleanup_chrome_launcher() {
  local socket_pid=""

  for socket_pid in "${socket_pids[@]}"; do
    kill "$socket_pid" >/dev/null 2>&1 || true
    wait "$socket_pid" >/dev/null 2>&1 || true
  done

  rm -f "$local_x11_socket"
  rm -rf "$wayland_runtime_dir"
  if [ "$created_x11_dir" -eq 1 ]; then
    rmdir /tmp/.X11-unix >/dev/null 2>&1 || true
  fi

  if [ "$local_suite" -eq 1 ]; then
    cleanup_suite
  fi
}
trap cleanup_chrome_launcher EXIT

start_unix_socket() {
  local socket_path="$1"
  local socket_pid=""

  mkdir -p "$(dirname "$socket_path")"
  rm -f "$socket_path"
  socat "UNIX-LISTEN:$socket_path,fork" EXEC:/bin/true >/dev/null 2>&1 &
  socket_pid="$!"
  socket_pids+=("$socket_pid")

  for _ in $(seq 1 50); do
    [ ! -S "$socket_path" ] || return 0
    sleep 0.1
  done

  fail "Unix socket was not created: $socket_path"
}

write_generated_display() {
  local display_value="$1"

  cat >"$fixture_dir/.devcontainer/.env" <<EOF
# .env - generated by .devcontainer/initialize.sh
DEVCONTAINER_DISPLAY=$display_value
EOF
}

assert_no_wayland_ozone_arg() {
  if grep -Fx -- "--ozone-platform=wayland" "$args_capture_file" >/dev/null; then
    fail "chrome launcher selected Wayland unexpectedly"
  fi
}

mkdir -p "$fixture_dir/.devcontainer" "$fake_bin" "$wayland_runtime_dir"
chmod 700 "$wayland_runtime_dir"

cat >"$fake_bin/google-chrome" <<'EOF'
#!/usr/bin/env bash
{
  printf 'DISPLAY=%s\n' "${DISPLAY:-}"
  printf 'WAYLAND_DISPLAY=%s\n' "${WAYLAND_DISPLAY:-}"
  printf 'XDG_RUNTIME_DIR=%s\n' "${XDG_RUNTIME_DIR:-}"
} >"$CHROME_LAUNCHER_CAPTURE"
printf '%s\n' "$@" >"$CHROME_LAUNCHER_ARGS_CAPTURE"
EOF
chmod +x "$fake_bin/google-chrome"

write_generated_display "localhost:77.0"
env -u WAYLAND_DISPLAY -u XDG_RUNTIME_DIR \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" about:blank

grep -Fx "DISPLAY=localhost:77.0" "$capture_file" >/dev/null \
  || fail "chrome launcher did not refresh DISPLAY from generated workspace env"
grep -Fx -- "--user-data-dir=$workspace_profile_dir" "$args_capture_file" >/dev/null \
  || fail "chrome launcher did not use workspace .chrome as visible profile"
assert_no_wayland_ozone_arg
for expected_arg in \
  --disable-background-networking \
  --disable-breakpad \
  --disable-component-update \
  --disable-default-apps \
  --disable-extensions \
  --disable-gpu \
  --disable-notifications \
  --disable-search-engine-choice-screen \
  --disable-sync \
  --disable-translate \
  --metrics-recording-only \
  --mute-audio \
  --password-store=basic; do
  grep -Fx -- "$expected_arg" "$args_capture_file" >/dev/null \
    || fail "chrome launcher did not pass visible performance flag: $expected_arg"
done

env -u WAYLAND_DISPLAY -u XDG_RUNTIME_DIR \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  DISPLAY=localhost:1.0 \
  "$project_root/scripts/chrome.sh" --user-data-dir="$explicit_profile_dir" about:blank

grep -Fx "DISPLAY=localhost:77.0" "$capture_file" >/dev/null \
  || fail "chrome launcher did not replace stale DISPLAY from generated workspace env"
grep -Fx -- "--user-data-dir=$explicit_profile_dir" "$args_capture_file" >/dev/null \
  || fail "chrome launcher did not forward explicit caller profile"
if grep -Fx -- "--user-data-dir=$workspace_profile_dir" "$args_capture_file" >/dev/null; then
  fail "chrome launcher added workspace .chrome despite explicit caller profile"
fi
[[ "$(grep -c '^--user-data-dir' "$args_capture_file")" = "1" ]] \
  || fail "chrome launcher passed more than one user data directory"

start_unix_socket "$wayland_socket_path"
write_generated_display ":$invalid_display_number"
WAYLAND_DISPLAY="$wayland_socket_name" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  DISPLAY=localhost:1.0 \
  "$project_root/scripts/chrome.sh" about:blank

grep -Fx "DISPLAY=" "$capture_file" >/dev/null \
  || fail "chrome launcher did not remove invalid X11 DISPLAY when selecting Wayland"
grep -Fx "WAYLAND_DISPLAY=$wayland_socket_name" "$capture_file" >/dev/null \
  || fail "chrome launcher did not preserve WAYLAND_DISPLAY"
grep -Fx -- "--ozone-platform=wayland" "$args_capture_file" >/dev/null \
  || fail "chrome launcher did not force the Wayland Ozone backend"

if [ ! -d /tmp/.X11-unix ]; then
  mkdir -m 1777 /tmp/.X11-unix
  created_x11_dir=1
fi
start_unix_socket "$local_x11_socket"
write_generated_display ":$local_display_number.0"
env -u WAYLAND_DISPLAY -u XDG_RUNTIME_DIR \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" about:blank

grep -Fx "DISPLAY=:$local_display_number.0" "$capture_file" >/dev/null \
  || fail "chrome launcher did not preserve a local X11 display with a real socket"
assert_no_wayland_ozone_arg

write_generated_display "host.docker.internal:4.0"
WAYLAND_DISPLAY="missing-wayland.sock" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" about:blank

grep -Fx "DISPLAY=host.docker.internal:4.0" "$capture_file" >/dev/null \
  || fail "chrome launcher did not preserve a caller-managed remote X11 display"
assert_no_wayland_ozone_arg

write_generated_display ":$invalid_display_number"
rm -f "$capture_file" "$args_capture_file" "$error_capture_file"
set +e
WAYLAND_DISPLAY="missing-wayland.sock" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" about:blank 2>"$error_capture_file"
launcher_status="$?"
set -e

[[ "$launcher_status" -ne 0 ]] || fail "chrome launcher accepted unusable visible displays"
[ ! -e "$capture_file" ] || fail "chrome launcher started google-chrome with unusable displays"
grep -F "Detected DISPLAY=:$invalid_display_number, but /tmp/.X11-unix/X$invalid_display_number is not available inside the container." "$error_capture_file" >/dev/null \
  || fail "chrome launcher did not explain the missing local X11 socket"
grep -F "Detected WAYLAND_DISPLAY=missing-wayland.sock, but no socket is available at $wayland_runtime_dir/missing-wayland.sock." "$error_capture_file" >/dev/null \
  || fail "chrome launcher did not explain the missing Wayland socket"

rm -f "$capture_file" "$args_capture_file"
DISPLAY=":$invalid_display_number" \
  WAYLAND_DISPLAY="missing-wayland.sock" \
  XDG_RUNTIME_DIR="$wayland_runtime_dir" \
  PATH="$fake_bin:$PATH" \
  DEVCONTAINER_WORKSPACE_FOLDER="$fixture_dir" \
  CHROME_LAUNCHER_CAPTURE="$capture_file" \
  CHROME_LAUNCHER_ARGS_CAPTURE="$args_capture_file" \
  "$project_root/scripts/chrome.sh" --headless --version

grep -Fx -- "--headless=new" "$args_capture_file" >/dev/null \
  || fail "chrome launcher changed the headless Chrome path"

pass "chrome launcher selects usable display backends and rejects missing local sockets"
